### ISSUE TITLE
FabIO does not compile on Python 3.7

### ISSUE THREAD

**Issue by kif** [silx-kit/fabio#241]
```
c:\python37\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumP
y API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
fabio\ext\cf_io.c(5726): warning C4020: 'function through pointer': too many actual parameters
fabio\ext\cf_io.c(6779): error C2039: 'exc_type': is not a member of '_ts'
c:\python37\include\pystate.h(209): note: see declaration of '_ts'
fabio\ext\cf_io.c(6780): error C2039: 'exc_value': is not a member of '_ts'
c:\python37\include\pystate.h(209): note: see declaration of '_ts'
fabio\ext\cf_io.c(6781): error C2039: 'exc_traceback': is not a member of '_ts'
c:\python37\include\pystate.h(209): note: see declaration of '_ts'
fabio\ext\cf_io.c(6788): error C2039: 'exc_type': is not a member of '_ts'
c:\python37\include\pystate.h(209): note: see declaration of '_ts'
fabio\ext\cf_io.c(6789): error C2039: 'exc_value': is not a member of '_ts'
c:\python37\include\pystate.h(209): note: see declaration of '_ts'
fabio\ext\cf_io.c(6790): error C2039: 'exc_traceback': is not a member of '_ts'
c:\python37\include\pystate.h(209): note: see declaration of '_ts'
fabio\ext\cf_io.c(6791): error C2039: 'exc_type': is not a member of '_ts'
c:\python37\include\pystate.h(209): note: see declaration of '_ts'
fabio\ext\cf_io.c(6792): error C2039: 'exc_value': is not a member of '_ts'
c:\python37\include\pystate.h(209): note: see declaration of '_ts'
fabio\ext\cf_io.c(6793): error C2039: 'exc_traceback': is not a member of '_ts'
c:\python37\include\pystate.h(209): note: see declaration of '_ts'
fabio\ext\cf_io.c(6848): error C2039: 'exc_type': is not a member of '_ts'
c:\python37\include\pystate.h(209): note: see declaration of '_ts'
fabio\ext\cf_io.c(6849): error C2039: 'exc_value': is not a member of '_ts'
c:\python37\include\pystate.h(209): note: see declaration of '_ts'
fabio\ext\cf_io.c(6850): error C2039: 'exc_traceback': is not a member of '_ts'
c:\python37\include\pystate.h(209): note: see declaration of '_ts'
fabio\ext\cf_io.c(6851): error C2039: 'exc_type': is not a member of '_ts'
c:\python37\include\pystate.h(209): note: see declaration of '_ts'
fabio\ext\cf_io.c(6852): error C2039: 'exc_value': is not a member of '_ts'
c:\python37\include\pystate.h(209): note: see declaration of '_ts'
fabio\ext\cf_io.c(6853): error C2039: 'exc_traceback': is not a member of '_ts'
c:\python37\include\pystate.h(209): note: see declaration of '_ts'
fabio\ext\cf_io.c(7264): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
fabio\ext\cf_io.c(7270): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDE
BUG /MD -Ifabio\ext\include -IC:\Python37\lib\site-packages\numpy\core\include -IC:\Python37\include -IC:\Python37\inclu
de -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Microsoft Visual Studio
14.0\VC\ATLMFC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" -I"C:\Program Files (x86)\W
indows Kits\NETFXSDK\4.6.1\include\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" -I"C:\Prog
ram Files (x86)\Windows Kits\10\include\10.0.16299.0\um" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\
winrt" /Tcfabio\ext\cf_io.c /Fobuild\temp.win-amd64-3.7\Release\fabio\ext\cf_io.obj" failed with exit status 2
```

**Comment by kif** [comment]
Actually it is another bug: Files were not re-cythonized !
I will send the window, mac and linux  wheels on pypi
